# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-20 20:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0015_auto_20180328_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_msg', models.TextField(blank=True, default=b'')),
                ('signature', models.TextField(blank=True, default=b'')),
                ('is_valid', models.BooleanField(default=False)),
                ('txid', models.TextField(blank=True, default=b'')),
                ('previous_hash', models.TextField(blank=True, default=b'')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.Block')),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='block',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='private_key',
        ),
        migrations.AddField(
            model_name='prescription',
            name='encrypted_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='prescription',
            name='public_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='prescription',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='details',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='extras',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='location',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_cedula',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_hospital',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medic_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_age',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='previous_hash',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='public_key',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rxid',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='blockchain.Transaction'),
        ),
    ]
