# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0016_auto_20180720_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='public_data',
            new_name='data',
        ),
    ]
