# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0017_auto_20180527_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.Block'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='previous_hash',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
