# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0018_auto_20180606_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='blockchain.Transaction'),
        ),
    ]
