# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0018_auto_20180726_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='files',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
